project:
  type: website

website:
  title: "Documentation projet cartiflette"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      light: [minty, styles.scss]
      dark: sketchy
    css: styles.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 2000px
      margin-width: 0px
      gutter-width: 0.5rem


output: false