name: Publish slides

on: 
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Render website
        run: |
          rm _quarto.yml
          cp _quarto-prod.yml _quarto.yml
          quarto render --profile complete --to html
      - name: Publish to Pages
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.email quarto-github-actions-publish@example.com
          git config --global user.name "Quarto GHA Workflow Runner"
          quarto publish gh-pages . --no-render --no-browser
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}