name: Publish website

on: 
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          pip install -r requirements.txt
          pip install geopandas -U 

      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.5.57

      - name: Render FR version
        uses: quarto-dev/quarto-actions/render@v2
        env:
          QUARTO_PROFILE: complete
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          render: false
          target: gh-pages
  build-notebook:
    runs-on: inseefrlab/onyxia-vscode-python:py3.12.4-2024.09.09
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure safe.directory  # Workaround for actions/checkout#760
        run: |
          git config --global --add safe.directory /__w/cartiflette-website/cartiflette-website
          git config --global --add safe.directory /__w/cartiflette-website/cartiflette-notebooks
          git config --global --add safe.directory /tmp/
        
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          pip install -r requirements.txt
          pip install geopandas -U 

      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.5.57

      - name: Convert in ipynb with Quarto
        run: |
          quarto render --profile complete --to ipynb
          mc cp _site/use-case/ s3/projet-cartiflette/resources/notebooks
